#!@bash@/bin/bash
# code: language=bash tabSize=4
# This file contains code from https://github.com/ryantm/agenix/blob/master/pkgs/agenix.nix and https://github.com/nzbr/nixos/blob/main/scripts.nix

for input in "$@"; do
    if ! [ -f "$input" ]; then
        echo input file \"$input\" does not exist
        exit 1
    fi

    if [ -e "${input}.age" ]; then
        echo output file \"${input}.age\" already exists, aborting
        exit 1
    fi
done

nixInstantiate=@nixFlakes@/bin/nix-instantiate
sedBin=@gnused@/bin/sed
ageBin=@rage@/bin/rage

set -euxo pipefail

RULES=${RULES:-./secrets.nix}

for input in "$@"; do
    FILE="${input}.age"

    KEYS=$((${nixInstantiate} --eval -E "(let rules = import $RULES; in builtins.concatStringsSep \"\n\" rules.\"$FILE\".publicKeys)" | ${sedBin} 's/"//g' | ${sedBin} 's/\\n/\n/g') || exit 1)

    if [ -z "$KEYS" ]
    then
        >&2 echo "There is no rule for $FILE in $RULES."
        exit 1
    fi

    ENCRYPT=()
    while IFS= read -r key
    do
        ENCRYPT+=(--recipient "$key")
    done <<< "$KEYS"

    ${ageBin} -a "${ENCRYPT[@]}" -o "${FILE}" < "${input}"
    rm "$input"
done
