name: Build Live ISO 💿

on:
  workflow_call: {}
  workflow_dispatch: {}
  schedule:
    - cron: "0 8 15 */3 *"

jobs:
  iso:
    name: Build ISO 💿
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build ISO 💿
        uses: nzbr/actions/nix-build@main
        with:
          expression: .#nixosConfigurations.live.config.system.build.isoImage
          cache: true
          cache-tag: live-iso
          secret-key: ${{ secrets.SECRET_DECRYPTION_KEY }}

      - name: Upload ISO 📤
        uses: actions/upload-artifact@v4
        with:
          name: live-iso
          path: result/iso/*.iso
