name: Pull Request 📨

on:
  pull_request: {}

jobs:
  checks:
    uses: nzbr/actions/.github/workflows/run_checks.yml@main
    secrets:
      SECRET_DECRYPTION_KEY: ${{ secrets.SECRET_DECRYPTION_KEY }}

  build:
    uses: ./.github/workflows/run_build_default_hosts.yml
    secrets: inherit
