name: Build Default Hosts 🛠️

on:
  workflow_call: {}

jobs:
  build:
    name: Build Host Config 🛠️
    strategy:
      fail-fast: false
      matrix:
        host:
          - earthquake
          - firestorm
          - permafrost
          - pulsar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build toplevel ❄️
        uses: nzbr/actions/nix-build@main
        with:
          expression: .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
          cache: true
          cache-tag: ${{ matrix.host }}
          secret-key: ${{ secrets.SECRET_DECRYPTION_KEY }}
