name: Build Default Hosts 🛠️

on:
  workflow_call: {}

jobs:
  build:
    name: Build Host Config 🛠️
    strategy:
      fail-fast: false
      matrix:
        config:
          - '{"runner": "ubuntu-24.04", "host": "earthquake"}'
          - '{"runner": "ubuntu-24.04", "host": "firestorm"}'
          - '{"runner": "ubuntu-24.04", "host": "permafrost"}'
          - '{"runner": "ubuntu-24.04", "host": "pulsar"}'
          - '{"runner": "ubuntu-24.04-arm", "host": "buildpi"}'
          - '{"runner": "ubuntu-24.04-arm", "host": "shockwave"}'
    runs-on: ${{ fromJson(matrix.config).runner }}
    env:
      HOST: ${{ fromJson(matrix.config).host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build toplevel ❄️
        uses: nzbr/actions/nix-build@main
        with:
          expression: .#nixosConfigurations.${{ env.HOST }}.config.system.build.toplevel
          cache: true
          cache-tag: ${{ env.HOST }}
          secret-key: ${{ secrets.SECRET_DECRYPTION_KEY }}
