inputs:
  expression:
    description: 'Nix expression to build'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check for nix ✅
      id: check-nix
      shell: bash
      run: |
        if command -v nix &> /dev/null
        then
          echo "nix-found=true" | tee -a $GITHUB_OUTPUT
        else
          echo "nix-found=false" | tee -a $GITHUB_OUTPUT
        fi

    - name: Install nix ❄️
      uses: ./.github/actions/install-nix
      if: ${{ steps.check-nix.outputs.nix-found != 'true' }}

    - name: Build ${{ inputs.expression }} 🛠️
      shell: bash
      run: nix build -L "${{ inputs.expression }}"
